module redis {
    requires org.slf4j;
    requires org.slf4j.simple;
    requires transitive micrometer.core;
    requires micrometer.registry.prometheus;
    requires io.prometheus.metrics.core;
    requires transitive jdk.httpserver;

    exports blocking;
    exports collections;
    exports commands.base;
    exports commands.core;
    exports commands.context;
    exports commands.registry;
    exports commands.impl.replication;
    exports commands.impl.config;
    exports commands.result;
    exports commands.impl.basic;
    exports commands.impl.lists;
    exports commands.impl.sortedsets;
    exports commands.impl.streams;
    exports commands.impl.strings;
    exports commands.impl.transaction;
    exports commands.impl.pubsub;
    exports events;
    exports errors;
    exports protocol;
    exports pubsub;
    exports server;
    exports server.http;
    exports replication;
    exports storage;
    exports storage.expiry;
    exports storage.persistence;
    exports storage.repositories;
    exports storage.types;
    exports storage.types.streams;
    exports scheduler;
    exports transaction;
    exports commands.validation;
    exports config;
    exports utils;
    exports metrics;
}
